# Generated by Django 4.2.7 on 2024-02-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('fromtime', models.TimeField(blank=True, null=True)),
                ('totime', models.TimeField(blank=True, null=True)),
                ('workout', models.CharField(max_length=100)),
                ('workoutcate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='offlinetraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('plan', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='New', max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='onlinetraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('plan', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='New', max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paymenttrainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(max_length=240, null=True)),
                ('name', models.CharField(max_length=240, null=True)),
                ('sname', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifsc', models.CharField(max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paymenttrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(max_length=240, null=True)),
                ('name', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifsc', models.CharField(max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('username', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='trainee', max_length=240, null=True)),
            ],
        ),
    ]
